LABELS = [
    "Bạn đọc",
    "Bảo vệ người tiêu dùng",
    "Bất động sản",
    "Chính trị",
    "Công nghệ",
    "Dân tộc - Tôn giáo",
    "Đời sống",
    "Du lịch",
    "Giáo dục",
    "Kinh doanh",
    "Ô tô - Xe máy",
    "Pháp luật",
    "Sức khỏe",
    "Thế giới",
    "Thể thao",
    "Thị trường tiêu dùng",
    "Thời sự",
    "Tuần Việt Nam",
    "Văn hóa - Giải trí",
]

KEYWORD_HINTS: dict[str, tuple[str, ...]] = {
    "Công nghệ": (
        "ai",
        "chip",
        "phobert",
        "gpu",
        "gói",
        "hạ tầng",
        "grpc",
        "gRPC",
        "mô hình",
        "công nghệ",
        "technology",
        "model",
        "models",
        "inference",
        "pipeline",
        "automation",
    ),
    "Giáo dục": (
        "trường",
        "học sinh",
        "đại học",
        "thi",
        "tuyển sinh",
        "giáo dục",
        "school",
        "schools",
        "student",
        "students",
        "university",
        "universities",
        "exam",
        "exams",
        "admissions",
    ),
    "Kinh doanh": ("doanh nghiệp", "thị trường", "kinh doanh", "đầu tư", "xuất khẩu", "business", "market", "investment", "company", "sales"),
    "Bất động sản": ("dự án", "bất động sản", "nhà đất", "căn hộ", "real estate", "property", "apartment", "housing"),
    "Chính trị": ("quốc hội", "chính phủ", "đảng", "nghị quyết", "chính trị", "government", "assembly", "decree", "policy", "minister"),
    "Thời sự": ("xã hội", "địa phương", "tai nạn", "thời sự", "điều tra", "news", "local", "breaking", "incident", "society"),
    "Thế giới": ("quốc tế", "thế giới", "mỹ", "châu âu", "trung quốc", "world", "international", "china", "europe"),
    "Sức khỏe": ("bệnh viện", "y tế", "sức khỏe", "bác sĩ", "thuốc", "health", "hospital", "doctor", "medical", "medicine"),
    "Thể thao": ("bóng đá", "vô địch", "cầu thủ", "hlv", "thể thao", "sports", "football", "player", "coach", "match"),
    "Văn hóa - Giải trí": ("ca sĩ", "giải trí", "nghệ sĩ", "phim", "văn hóa", "culture", "entertainment", "singer", "movie", "artist"),
}
